use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    emit_data_includes();
    #[cfg(feature = "ocr")]
    emit_ocr_includes();
}

#[cfg(feature = "ocr")]
const OCR_MODELS: &[&str] = &["text-detection.rten", "text-recognition.rten"];
#[cfg(feature = "ocr")]
const OCR_MODELS_BASE_URL: &str = "https://ocrs-models.s3-accelerate.amazonaws.com";

#[cfg(feature = "ocr")]
fn emit_ocr_includes() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let models_dir = Path::new(&manifest_dir).join("models");
    fs::create_dir_all(&models_dir).expect("cannot create engine/models");

    let mut out = String::from("// Auto-generated by engine/build.rs — do not edit.\n\n");
    for file in OCR_MODELS {
        let path = models_dir.join(file);
        if !path.is_file() {
            let url = format!("{OCR_MODELS_BASE_URL}/{file}");
            let status = std::process::Command::new("curl")
                .args(["-sSL", "--fail", "-o"])
                .arg(&path)
                .arg(&url)
                .status()
                .unwrap_or_else(|e| panic!("cannot run curl for {url}: {e}"));
            if !status.success() {
                let _ = fs::remove_file(&path);
                panic!("failed to download OCR model {url} (curl exit {status})");
            }
        }
        let canonical = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", path.display()));
        let const_name = file
            .trim_end_matches(".rten")
            .replace('-', "_")
            .to_uppercase();
        out.push_str(&format!(
            "pub const {}: &[u8] = include_bytes!({:?});\n",
            const_name, canonical
        ));
        println!("cargo:rerun-if-changed={}", canonical.display());
    }

    let dest = Path::new(&out_dir).join("ocr_includes.rs");
    fs::write(&dest, out).expect("failed to write ocr_includes.rs");
}

fn emit_data_includes() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let data_root = Path::new(&manifest_dir).join("..").join("data");
    let data_root = data_root
        .canonicalize()
        .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", data_root.display()));

    let mut out = String::new();
    out.push_str("// Auto-generated by engine/build.rs — do not edit.\n\n");

    let singletons: &[(&str, &str)] = &[
        ("AFFIXES_JSON", "affixes.json"),
        ("AFFIX_TAGS_JSON", "affix-tags.json"),
        ("AUGMENTS_JSON", "augments.json"),
        ("CRYSTALS_JSON", "crystals.json"),
        ("GAME_CONFIG_JSON", "game-config.json"),
        ("INCARNATION_NODES_JSON", "incarnation-nodes.json"),
        ("ITEM_GRANTED_SKILLS_JSON", "item-granted-skills.json"),
        ("RUNEWORDS_JSON", "runewords.json"),
        ("SETS_JSON", "sets.json"),
        ("SUBSKILL_TAGS_JSON", "subskill-tags.json"),
    ];
    for (name, file) in singletons {
        let path = data_root.join(file);
        let canonical = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", path.display()));
        out.push_str(&format!(
            "pub const {}: &str = include_str!({:?});\n",
            name, canonical
        ));
        println!("cargo:rerun-if-changed={}", canonical.display());
    }

    let categories: &[(&str, &str)] = &[
        ("CLASSES_JSON", "classes"),
        ("GEMS_JSON", "gems"),
        ("ITEMS_JSON", "items"),
        ("RUNES_JSON", "runes"),
        ("SKILLS_JSON", "skills"),
    ];
    for (const_name, dir) in categories {
        let dir_path = data_root.join(dir);
        let mut files: Vec<PathBuf> = fs::read_dir(&dir_path)
            .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", dir_path.display()))
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("json"))
            .collect();
        files.sort();

        out.push_str(&format!("\npub const {}: &[&str] = &[\n", const_name));
        for f in &files {
            let canonical = f
                .canonicalize()
                .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", f.display()));
            out.push_str(&format!("    include_str!({:?}),\n", canonical));
            println!("cargo:rerun-if-changed={}", canonical.display());
        }
        out.push_str("];\n");
        println!("cargo:rerun-if-changed={}", dir_path.display());
    }

    let seasons_dir = data_root.join("seasons");
    out.push_str("\npub const SEASON_PATCHES: &[(&str, &str)] = &[\n");
    if seasons_dir.is_dir() {
        let mut season_dirs: Vec<PathBuf> = fs::read_dir(&seasons_dir)
            .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", seasons_dir.display()))
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        season_dirs.sort();
        for sd in &season_dirs {
            let season_id = sd
                .file_name()
                .and_then(|s| s.to_str())
                .unwrap_or_else(|| panic!("non-UTF8 season dir name in {}", sd.display()));
            let mut files: Vec<PathBuf> = fs::read_dir(sd)
                .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", sd.display()))
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| {
                    p.file_name()
                        .and_then(|s| s.to_str())
                        .is_some_and(|n| n.ends_with(".patch.json"))
                })
                .collect();
            files.sort();
            for f in &files {
                let canonical = f
                    .canonicalize()
                    .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", f.display()));
                let file_name = f
                    .file_name()
                    .and_then(|s| s.to_str())
                    .unwrap_or_else(|| panic!("non-UTF8 patch file name in {}", f.display()));
                let rel = format!("{season_id}/{file_name}");
                out.push_str(&format!(
                    "    ({:?}, include_str!({:?})),\n",
                    rel, canonical
                ));
                println!("cargo:rerun-if-changed={}", canonical.display());
            }
            println!("cargo:rerun-if-changed={}", sd.display());
        }
        println!("cargo:rerun-if-changed={}", seasons_dir.display());
    }
    out.push_str("];\n");

    let dest = Path::new(&out_dir).join("data_includes.rs");
    fs::write(&dest, out).expect("failed to write data_includes.rs");

    emit_i18n_includes(&out_dir, &data_root);
}

// data/i18n/<lang>.json -> CATALOGS, data/i18n/ui/<lang>.json -> UI_CATALOGS.
// The two stay separate so that wrapping a literal that happens to match a game
// phrase cannot translate an identifier by accident. sources.json is the
// translator-facing template, not a catalogue, so it never ships.
fn emit_i18n_includes(out_dir: &str, data_root: &Path) {
    let i18n_dir = data_root.join("i18n");
    let mut out = String::from("// Auto-generated by engine/build.rs — do not edit.\n\n");
    emit_catalog_table(&mut out, "CATALOGS", &i18n_dir);
    emit_catalog_table(&mut out, "UI_CATALOGS", &i18n_dir.join("ui"));
    emit_catalog_table(&mut out, "CONTEXT_CATALOGS", &i18n_dir.join("context"));
    if i18n_dir.is_dir() {
        println!("cargo:rerun-if-changed={}", i18n_dir.display());
    }

    let dest = Path::new(out_dir).join("i18n_includes.rs");
    fs::write(&dest, out).expect("failed to write i18n_includes.rs");
}

fn emit_catalog_table(out: &mut String, const_name: &str, dir: &Path) {
    out.push_str(&format!("pub const {}: &[(&str, &str)] = &[\n", const_name));
    if dir.is_dir() {
        let mut files: Vec<PathBuf> = fs::read_dir(dir)
            .unwrap_or_else(|e| panic!("cannot read dir {}: {e}", dir.display()))
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| {
                p.extension().and_then(|s| s.to_str()) == Some("json")
                    && p.file_stem().and_then(|s| s.to_str()) != Some("sources")
            })
            .collect();
        files.sort();
        for f in &files {
            let canonical = f
                .canonicalize()
                .unwrap_or_else(|e| panic!("cannot canonicalise {}: {e}", f.display()));
            let lang = f
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or_else(|| panic!("non-UTF8 catalog name in {}", f.display()));
            out.push_str(&format!(
                "    ({:?}, include_str!({:?})),\n",
                lang, canonical
            ));
            println!("cargo:rerun-if-changed={}", canonical.display());
        }
        println!("cargo:rerun-if-changed={}", dir.display());
    }
    out.push_str("];\n\n");
}
