[package]
name = "hsplanner"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "hsplanner"
path = "src/main.rs"

[dependencies]
hsplanner-planner.workspace = true


hsplanner-build.workspace = true
hsplanner-engine.workspace = true
hsplanner-ui.workspace = true
hsplanner-library.workspace = true
gpui-kit.workspace = true
log.workspace = true
hsplanner-notes.workspace = true
anyhow = "1"
futures = "0.3"
semver = "1"
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
sys-locale = "=0.3.2"
reqwest_client = { package = "gpui-pre-reqwest-client", version = "=0.3.3" }

image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp", "gif"] }
uuid = { version = "1", features = ["v4"] }
